const DEFAULT_AUTH_RATE_LIMIT_ENV = {
  AUTH_LOGIN_RATE_LIMIT_MAX_PER_ACCOUNT: "1000",
  AUTH_LOGIN_RATE_LIMIT_MAX_PER_IP: "5000",
  AUTH_REGISTER_RATE_LIMIT_MAX_PER_ACCOUNT: "1000",
  AUTH_REGISTER_RATE_LIMIT_MAX_PER_IP: "5000",
} as const;

export function buildE2EBackendEnv(
  overrides: NodeJS.ProcessEnv = {},
): NodeJS.ProcessEnv {
  return {
    ...process.env,
    AUTH_LOGIN_RATE_LIMIT_MAX_PER_ACCOUNT:
      process.env.AUTH_LOGIN_RATE_LIMIT_MAX_PER_ACCOUNT
      ?? DEFAULT_AUTH_RATE_LIMIT_ENV.AUTH_LOGIN_RATE_LIMIT_MAX_PER_ACCOUNT,
    AUTH_LOGIN_RATE_LIMIT_MAX_PER_IP:
      process.env.AUTH_LOGIN_RATE_LIMIT_MAX_PER_IP
      ?? DEFAULT_AUTH_RATE_LIMIT_ENV.AUTH_LOGIN_RATE_LIMIT_MAX_PER_IP,
    AUTH_REGISTER_RATE_LIMIT_MAX_PER_ACCOUNT:
      process.env.AUTH_REGISTER_RATE_LIMIT_MAX_PER_ACCOUNT
      ?? DEFAULT_AUTH_RATE_LIMIT_ENV.AUTH_REGISTER_RATE_LIMIT_MAX_PER_ACCOUNT,
    AUTH_REGISTER_RATE_LIMIT_MAX_PER_IP:
      process.env.AUTH_REGISTER_RATE_LIMIT_MAX_PER_IP
      ?? DEFAULT_AUTH_RATE_LIMIT_ENV.AUTH_REGISTER_RATE_LIMIT_MAX_PER_IP,
    ...overrides,
  };
}
